### ISSUE TITLE
Duplicate txs

### ISSUE THREAD

**Issue by strictlymomo** [ava-labs/ortelius#51] opened 2020-09-07 15:24 UTC
Saw a bunch of dups appear in the transactions endpoint around 2020-08-31 at 8 25 19 PM.

![Screen Shot 2020-08-31 at 8 25 19 PM](https://user-images.githubusercontent.com/8671427/92401806-6aa75f00-f0fc-11ea-8a43-a06b9133cf65.png)

Example ID: `2jBHZ8fb8LfeCdSGyNwWw2yrKRyeNeLZ7DUDPVKD6hbTTbs5ea`

**Comment by tyler-smith** [comment] 2020-09-08 04:08
Duplicate of #36, closing to consolidate.

**Closed by tyler-smith** 2020-09-08 04:08 UTC
